import { lineCardHint, lineDetails } from './lines.mjs';
import { normalize, categories, depths, grounds, regions, formatWeight as weight, rarityTiers, filterFish } from './core.mjs';
const $ = id => document.getElementById(id);
const E = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const num = n => new Intl.NumberFormat('ru-RU',{maximumFractionDigits:4}).format(n);
let data, fishByKey, locationByKey, activeFish = null, toastTimer;
let savedFavorites=[];
try { const value=JSON.parse(localStorage.getItem('anomfish-atlas-favorites')||'[]'); if(Array.isArray(value)) savedFavorites=value.filter(v=>typeof v==='string'); } catch {}
const defaults={query:'',category:'all',region:'',location:'',depth:'',bottom:[],method:'',bait:'',lure:'',available:false};
const state={...defaults,bottom:[],sort:'name',view:'grid',favorites:savedFavorites,favoritesOnly:false,compare:[],limit:24};
document.querySelectorAll('button,input,select').forEach(el=>el.disabled=true);
$('main').setAttribute('aria-busy','true');
function notify(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
function image(f,extra=''){return f.image?`<img src="${E(f.image)}" alt="${E(f.name)}" ${extra}>`:`<span class="location-no-image" aria-hidden="true">${icon('pin')}</span>`;}
function groundList(f){return `<div class="ground-list">${f.bottom.map(b=>`<span><i class="ground ${b}" aria-hidden="true"></i>${grounds[b]}</span>`).join('')}</div>`;}
function depthGlyph(depth){return `<span class="depth-glyph ${depth}" aria-hidden="true"><i></i><i></i><i></i></span>`;}
function aggressionBars(f){return `<span class="aggression-bars" aria-hidden="true">${Array.from({length:6},(_,i)=>`<i class="${i<f.agressiveRate/100?'on':''}"></i>`).join('')}</span>`;}
function fishCard(f){const fav=state.favorites.includes(f.key), compared=state.compare.includes(f.key);return `<article class="fish-card" data-type="${f.type}">
  <button class="icon-button card-favorite ${fav?'selected':''}" data-favorite="${f.key}" aria-pressed="${fav}" aria-label="${fav?'Убрать из избранного':'В избранное'}: ${E(f.name)}">${icon('heart')}</button>
  <button class="card-open" data-open="${f.key}" aria-label="Открыть карточку: ${E(f.name)}"><div class="fish-stage"><span class="category-tag">${categories[f.type]}</span>${image(f,'loading="lazy" decoding="async"')}<span class="depth-badge">${depthGlyph(f.depth)}${{small:'Небольшая глубина',medium:'Средняя глубина',bottom:'У дна'}[f.depth]}</span>${f.tackleBait?'<span class="spinning-badge">Спиннинг</span>':''}</div>
  <div class="card-body"><h2 class="fish-name">${E(f.name)}</h2><p class="fish-en">${E(f.nameEn)}</p><div class="card-metrics"><div><div class="metric-label">Обычный вес</div><div class="metric-value">${weight(f.minWeight)} – ${weight(f.maxWeight)}</div></div><div><div class="metric-label">Агрессивность</div><div class="metric-value aggression-value">${aggressionBars(f)}×${num(f.agressiveRate/100)}</div></div></div>${groundList(f)}${lineCardHint(f)}</div></button>
  <div class="card-bottom"><div class="bait-stack" aria-label="Наживки: ${E(f.bait.map(k=>data.items[k].name).join(', ')||'нет')}">${f.bait.slice(0,4).map(k=>image(data.items[k],`loading="lazy" title="${E(data.items[k].name)}"`)).join('')}${f.bait.length>4?`<span>+${f.bait.length-4}</span>`:f.bait.length===0?'<span>Без наживки</span>':''}</div><button class="card-compare ${compared?'selected':''}" data-compare="${f.key}" aria-pressed="${compared}" aria-label="${compared?'Убрать из сравнения':'Сравнить'}: ${E(f.name)}">${icon(compared?'check':'compare')}${compared?'Добавлено':'Сравнить'}</button></div></article>`;}
function getRows(){return filterFish(data,state);}
function countFilters(){return ['region','location','depth','method','bait','lure','available'].filter(k=>!!state[k]).length+state.bottom.length;}
function fillOptions(){
  const sorted=[...Object.values(data.items)].sort((a,b)=>a.name.localeCompare(b.name,'ru'));
  for(const type of ['bait','lure']) $(type).innerHTML=`<option value="">${type==='bait'?'Любая наживка':'Любая прикормка'}</option>`+sorted.filter(i=>i.type===type).map(i=>`<option value="${i.key}">${E(i.name)}</option>`).join('');
  fillLocations();
}
function fillLocations(){const locs=data.locations.filter(l=>!state.region||l.region===state.region).sort((a,b)=>a.rank-b.rank||a.name.localeCompare(b.name,'ru'));
  $('location').innerHTML='<option value="">Все водоёмы</option>'+[true,false].map(active=>`<optgroup label="${active?'Активные':'Отключённые в данных игры'}">${locs.filter(l=>l.enabled===active).map(l=>`<option value="${l.key}">${E(l.name)} · ${l.minFishLevel}–${l.maxFishLevel}</option>`).join('')}</optgroup>`).join('');
  $('location').value=state.location;
}
function renderTabs(){const base=filterFish(data,{...state,category:'all'});$('categories').innerHTML=Object.entries(categories).map(([key,label])=>`<button data-category="${key}" class="${state.category===key?'active':''}" aria-pressed="${state.category===key}">${label}<span>${key==='all'?base.length:base.filter(f=>f.type===key).length}</span></button>`).join('');}
function renderChips(){const chips=[];if(state.region)chips.push(['region',regions[state.region]]);if(state.location)chips.push(['location',locationByKey.get(state.location)?.name]);if(state.depth)chips.push(['depth',depths[state.depth]]);state.bottom.forEach(b=>chips.push(['bottom:'+b,grounds[b]]));if(state.method)chips.push(['method',state.method==='spinning'?'Спиннинг':'На наживку']);if(state.bait)chips.push(['bait',data.items[state.bait].name]);if(state.lure)chips.push(['lure',data.items[state.lure].name]);if(state.available)chips.push(['available','Активные водоёмы']);$('active-filters').innerHTML=chips.map(([key,label])=>`<button class="filter-chip" data-clear="${E(key)}">${E(label)}${icon('close')}<span class="sr-only">Убрать фильтр</span></button>`).join('');}
function syncControls(){for(const k of ['region','location','method','bait','lure'])$(k).value=state[k];$('available').checked=state.available;$('search').value=state.query;$('sort').value=state.sort;document.querySelectorAll('[data-depth]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.depth===state.depth)));document.querySelectorAll('[data-bottom]').forEach(b=>b.setAttribute('aria-pressed',String(state.bottom.includes(b.dataset.bottom))));document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-pressed',String(b.dataset.view===state.view));});$('catalog-tab').classList.toggle('active',!state.favoritesOnly);$('favorites-tab').classList.toggle('active',state.favoritesOnly);$('fav-count').textContent=state.favorites.length;$('filter-count').textContent=countFilters()||'';}
function render(){const rows=getRows();renderTabs();syncControls();renderChips();$('result-count').innerHTML=`${state.favoritesOnly?'В избранном':'Найдено'} <strong>${rows.length}</strong> из ${state.favoritesOnly?state.favorites.length:data.fish.length} видов`;$('results').classList.toggle('list-view',state.view==='list');
  $('results').innerHTML=rows.length?rows.slice(0,state.limit).map(fishCard).join(''):`<div class="empty-state">${icon(state.favoritesOnly?'heart':'search')}<h2>${state.favoritesOnly&&!state.favorites.length?'Здесь будет ваш избранный улов':'Ничего не найдено'}</h2><p>${state.favoritesOnly&&!state.favorites.length?'Нажмите на сердечко у рыбы, чтобы сохранить её на этом устройстве.':'Попробуйте другое название или измените условия поиска.'}</p><button class="secondary-button" data-action="${state.favoritesOnly&&!state.favorites.length?'catalog':'reset'}">${state.favoritesOnly&&!state.favorites.length?'Открыть каталог':'Сбросить фильтры'}</button></div>`;
  $('load-more').hidden=rows.length<=state.limit;$('load-more').textContent=`Показать ещё ${Math.min(24,Math.max(0,rows.length-state.limit))} · осталось ${Math.max(0,rows.length-state.limit)}`;renderTray();
}
function refresh(){state.limit=24;render();}
function reset(){Object.assign(state,{...defaults,bottom:[]});fillLocations();refresh();}
function setFilter(key,value){state[key]=value;if(key==='region'){state.location='';fillLocations();}refresh();}
function toggleFavorite(key){if(!fishByKey.has(key))return;const before=state.favorites.includes(key);state.favorites=before?state.favorites.filter(k=>k!==key):[...state.favorites,key];try{localStorage.setItem('anomfish-atlas-favorites',JSON.stringify(state.favorites));}catch{notify('Сохранение недоступно. Избранное останется до закрытия страницы.');}render();if(activeFish===key&&$('detail-dialog').open)renderDetail(fishByKey.get(key));}
function toggleCompare(key){if(!fishByKey.has(key))return;if(state.compare.includes(key))state.compare=state.compare.filter(k=>k!==key);else{if(state.compare.length>=3){notify('Можно сравнить до трёх видов. Уберите один из выбранных.');return;}state.compare.push(key);}render();if(activeFish===key&&$('detail-dialog').open)renderDetail(fishByKey.get(key));}
function renderTray(){$('compare-tray').hidden=!state.compare.length;$('compare-tray').innerHTML=`<div class="tray-items">${state.compare.map(k=>{const f=fishByKey.get(k);return `<div class="tray-fish">${image(f)}<span>${E(f.name)}</span><button class="icon-button" data-compare="${k}" aria-label="Убрать ${E(f.name)} из сравнения">${icon('close')}</button></div>`;}).join('')}</div><button class="primary-button" id="run-compare" ${state.compare.length<2?'disabled':''}>${icon('compare')}Сравнить ${state.compare.length}/3</button><button class="text-button" data-action="clear-compare">Очистить</button>`;document.body.style.paddingBottom=state.compare.length?'84px':'';}
function showDialog(id){const dialog=$(id);if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');}
function closeDialog(id){$(id).close();}
function itemList(keys,type){if(!keys.length)return `<p class="note">${type==='bait'?'Не реагирует на наживки.':'Не реагирует на прикормки.'}</p>`;return `<div class="items-list">${keys.map(k=>{const i=data.items[k];return `<button class="item-chip" data-item="${k}" data-kind="${type}" title="Показать весь улов: ${E(i.name)}">${image(i,'loading="lazy"')}<span>${E(i.name)}${type==='lure'?`<small>Поклёвки: +${i.baitRate}%</small>`:''}</span></button>`;}).join('')}</div>`;}
function renderDetail(f){const tiers=rarityTiers(f,data.rarities),locs=f.locations.map(k=>locationByKey.get(k)).sort((a,b)=>Number(b.enabled)-Number(a.enabled)||a.rank-b.rank),fav=state.favorites.includes(f.key),compared=state.compare.includes(f.key);
  $('detail-content').innerHTML=`<div class="detail-top"><div class="detail-portrait">${image(f)}<span class="specimen-code">ВИД № ${String(f.uid).padStart(3,'0')} / V10</span></div><div class="detail-heading"><span class="detail-category">${categories[f.type]}</span><h2 id="detail-title">${E(f.name)}</h2><p class="name-en">${E(f.nameEn)}</p><div class="detail-actions"><button class="secondary-button" data-favorite="${f.key}" aria-pressed="${fav}">${icon('heart')}${fav?'В избранном':'В избранное'}</button><button class="secondary-button" data-compare="${f.key}" aria-pressed="${compared}">${icon(compared?'check':'compare')}${compared?'В сравнении':'Сравнить'}</button><button class="icon-button" data-copy="${f.key}" aria-label="Скопировать ссылку на ${E(f.name)}" title="Скопировать ссылку">${icon('pin')}</button><a class="seo-permalink" href="fish/${f.key}.html">Отдельная страница ↗</a></div></div></div>
  <div class="detail-layout"><div class="detail-left"><section class="detail-section"><div class="section-heading"><h3>Где держится</h3>${icon('wave')}</div><div class="depth-chart" role="img" aria-label="Глубина обитания: ${depths[f.depth]}">${Object.entries(depths).map(([k,v])=>`<div class="depth-row ${k===f.depth?'active':''}"><span>${v}</span>${k===f.depth?icon('check'):'<b>—</b>'}</div>`).join('')}</div><div class="habitat-tags">${f.bottom.map(b=>`<span><i class="ground ${b}"></i>${grounds[b]}</span>`).join('')}</div><p class="note">Глубина указана относительно глубины водоёма в точке заброса.</p>${f.tackleBait?`<div class="method-label">${icon('check')}Ловится на спиннинг</div>`:'<p class="note">На спиннинг не ловится.</p>'}</section>
  <section class="detail-section"><div class="meter-title"><span>Агрессивность</span><strong>×${num(f.agressiveRate/100)}</strong></div><div class="aggression-meter" role="img" aria-label="Агрессивность ${f.agressiveRate} процентов">${Array.from({length:6},(_,i)=>`<i class="${i<f.agressiveRate/100?'on':''}"></i>`).join('')}</div><p class="metric-note">Базовая сила сопротивления: вес × ${num(f.agressiveRate/100)}. Разница уровней рыбы и снасти может увеличить нагрузку.</p><div class="coefficient"><div class="meter-title"><span>Коэффициент выбора</span><strong>${num(f.rarity/f['rarity-max'])}</strong></div><div class="coefficient-bar" role="img" aria-label="Коэффициент ${f.rarity} / ${f['rarity-max']}"><span style="width:${100*(f.rarity/f['rarity-max'])/.5}%"></span></div><p class="metric-note">${f.rarity} / ${num(f['rarity-max'])}. Чем больше, тем выше базовый вес вида при выборе улова. Это не шанс поклёвки в процентах.</p></div></section></div>
  <div class="detail-right"><section class="detail-section"><div class="section-heading"><h3>Вес и редкость</h3><span>Пороги игры</span></div><div class="weight-summary"><strong>${weight(f.minWeight)} — ${weight(f.maxWeight)}</strong><span>обычный диапазон</span></div><div class="rarity-spectrum" aria-hidden="true">${tiers.map(t=>`<i style="--rarity:${t.color}"></i>`).join('')}</div><div class="tier-grid">${tiers.map((t,i)=>`<div class="tier-cell" style="--rarity:${t.color}"><span class="tier-name">${E(t.name)}</span><span class="tier-weight">${i===0?`${weight(t.min)} – &lt; ${weight(t.max)}`:`от ${weight(t.min)}`}</span></div>`).join('')}</div><p class="note">Порог следующей редкости завершает предыдущий диапазон. Трофей по условию игры — вес строго больше ${weight(f.maxWeight)}. Цветные сегменты обозначают редкости, а не пропорции веса.</p></section>
  ${lineDetails(f)}
  <section class="detail-section"><div class="section-heading"><h3>Наживки</h3><span>${f.bait.length} вариантов</span></div>${itemList(f.bait,'bait')}</section><section class="detail-section"><div class="section-heading"><h3>Прикормки</h3><span>${f.lure.length} вариантов</span></div>${itemList(f.lure,'lure')}<p class="note">Нажмите на наживку или прикормку, чтобы найти другой улов с теми же условиями.</p></section>
  <section class="detail-section"><div class="section-heading"><h3>Водоёмы</h3><span>${locs.filter(l=>l.enabled).length} активных</span></div>${locs.length?`<div class="locations-list">${locs.map(l=>`<button class="location-tile ${!l.enabled?'disabled':''}" data-place="${l.key}">${image(l,'loading="lazy"')}<span><strong>${E(l.name)}</strong><small>${regions[l.region]||E(l.region)} · ${l.minFishLevel}–${l.maxFishLevel} ур.</small><small>${l.enabled?`Разряд ${l.rank} · ${l.radTypes.includes('cold')?'Холод':'Радиация'} ${l.radRate}`:'Отключён в данных игры'}</small></span></button>`).join('')}</div>`:'<p class="note">В списках водоёмов клиента этот вид не указан. Постоянное место ловли по этим данным определить нельзя.</p>'}</section>
  <details class="raw-details"><summary>Все исходные параметры и пояснения</summary><table class="raw-table"><tbody>${rawRows(f).map(([label,key,value])=>`<tr><th>${label}<code>${key}</code></th><td>${E(value)}</td></tr>`).join('')}</tbody></table><p class="note">Параметр price не показан как итоговая стоимость продажи: она рассчитывается игрой с учётом других условий. rareWeight — опорный порог эпической редкости, а не максимальный возможный вес.</p></details></div></div>`;
}
function rawRows(f){return [['Игровой ключ','key',f.key],['Идентификатор','uid',f.uid],['Категория','type',categories[f.type]],['Кадр изображения','frameId',f.frameId],['Минимальный вес','minWeight',weight(f.minWeight)],['Максимальный обычный вес','maxWeight',weight(f.maxWeight)],['Опорный вес редкости','rareWeight',weight(f.rareWeight)],['Числитель коэффициента выбора','rarity',f.rarity],['Знаменатель коэффициента выбора','rarity-max',f['rarity-max']],['Исходный параметр цены','price',f.price],['Агрессивность','agressiveRate',f.agressiveRate+'%'],['Глубина','depth',depths[f.depth]],...Object.entries(grounds).map(([k,label])=>[label,'areal-'+k,f['areal-'+k]?'Да':'Нет']),['Спиннинг','tackleBait',f.tackleBait?'Да':'Нет'],['Наживки','bait',f.bait.map(k=>data.items[k].name).join(', ')||'Нет'],['Прикормки','lure',f.lure.map(k=>data.items[k].name).join(', ')||'Нет']];}
function openFish(key,updateUrl=true){const f=fishByKey.get(key);if(!f)return false;activeFish=key;renderDetail(f);showDialog('detail-dialog');$('detail-dialog').scrollTop=0;if(updateUrl&&location.hash!==`#fish=${key}`)history.pushState(null,'',`#fish=${encodeURIComponent(key)}`);document.title=`${f.name} · Атлас рыб AnomFish`;return true;}
function fromHash(){const match=location.hash.match(/^#fish=([^&]+)/);if(match){let key;try{key=decodeURIComponent(match[1]);}catch{return;}openFish(key,false);}else if($('detail-dialog').open)closeDialog('detail-dialog');}
function openComparison(){if(state.compare.length<2)return;const fishes=state.compare.map(k=>fishByKey.get(k));const maxWeight=Math.max(...fishes.map(f=>f.maxWeight));const rows=[
  ['Обычный вес',f=>`${weight(f.minWeight)} — ${weight(f.maxWeight)}<span class="comparison-meter" style="width:${100*f.maxWeight/maxWeight}%"></span>`],
  ['Эпический улов',f=>`от ${weight(f.rareWeight)}<small>Порог эпической редкости</small>`],
  ['Агрессивность',f=>`×${num(f.agressiveRate/100)}<span class="comparison-meter" style="width:${f.agressiveRate/6}%;background:var(--orange)"></span>`],
  ['Глубина',f=>depths[f.depth]],['Дно',f=>groundList(f)],['Спиннинг',f=>f.tackleBait?'Да':'Нет'],
  ['Наживки',f=>`<div class="tagline">${f.bait.map(k=>`<span class="mini-tag">${E(data.items[k].name)}</span>`).join('')||'Нет'}</div>`],
  ['Прикормки',f=>`<div class="tagline">${f.lure.map(k=>`<span class="mini-tag">${E(data.items[k].name)}</span>`).join('')||'Нет'}</div>`],
  ['Водоёмы',f=>f.locations.map(k=>{const l=locationByKey.get(k);return `${E(l.name)}${l.enabled?'':' (отключён)'}`;}).join(', ')||'Не указаны'],
  ['Коэффициент выбора',f=>`${num(f.rarity/f['rarity-max'])}<small>${f.rarity} / ${f['rarity-max']}; не вероятность поклёвки</small>`]
];$('compare-content').innerHTML=`<div class="comparison-scroll"><table class="comparison-table"><thead><tr><th>Параметр</th>${fishes.map(f=>`<td>${image(f)}<h3>${E(f.name)}</h3><small>${categories[f.type]}</small></td>`).join('')}</tr></thead><tbody>${rows.map(([label,fn])=>`<tr><th scope="row">${label}</th>${fishes.map(f=>`<td>${fn(f)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;showDialog('compare-dialog');}
function showAbout(){$('about-content').innerHTML=`<div class="about-body"><div class="data-counts"><span>${data.fish.length} видов улова</span><span>${data.locations.filter(l=>l.enabled).length} активных водоёмов</span><span>${Object.values(data.items).filter(i=>i.type==='bait').length} наживка</span><span>5 прикормок</span></div><section><h3>Снимок клиента v10</h3><p>Данные получены 29 сентября 2026 года из публичного каталога игры. Здесь перечислены все 137 записей улова: 76 рыб, 36 мутантов, 6 деликатесов и 19 находок. Оригинальные изображения сохранены вместе с каталогом. Отключённые водоёмы помечены отдельно. Автоматического обновления нет.</p></section><section><h3>Вес и редкость</h3><p>Обычный диапазон задан параметрами minWeight и maxWeight. Цветная шкала показывает последовательность редкостей; её сегменты одинаковой ширины и не передают числовое расстояние между порогами. Пороги рассчитаны по формуле клиента:</p><p class="formula">Δ = rareWeight − maxWeight<br>Необычный: maxWeight · Редкий: maxWeight + 0,5Δ<br>Эпический: maxWeight + Δ · Легендарный: maxWeight + 1,5Δ<br>Мифический: maxWeight + 2Δ · Мировой: maxWeight + 2,5Δ</p><p>Условие «трофей» в игре: вес строго больше maxWeight.</p></section><section><h3>Агрессивность и выбор улова</h3><p>Агрессивность ×2 означает базовую силу сопротивления вдвое больше веса. Шкала единая для всех видов: от ×1 до ×6. Уровень рыбы относительно снасти дополнительно влияет на силу. Коэффициент выбора = rarity / rarity-max. Он участвует в выборе вида вместе с условиями ловли, поэтому не равен вероятности поклёвки.</p></section><section><h3>Глубина, наживка, прикормка</h3><p>Глубина относительная: небольшая, средняя или дно. «Прикормки» соответствуют игровому каталогу lure; это отдельный параметр от ловли на спиннинг. Для специальных находок могут действовать дополнительные условия снастей, которые не перечислены в карточке вида.</p></section><section><h3>Избранное</h3><p>Избранное хранится только в этом браузере.</p></section></div>`;showDialog('about-dialog');}
function filterFromDetail(kind,key){Object.assign(state,{...defaults,bottom:[],favoritesOnly:false});state[kind]=key;fillLocations();refresh();closeDialog('detail-dialog');window.scrollTo({top:0,behavior:'smooth'});}
function mobileFilters(open){$('filters').classList.toggle('open',open);$('filter-shade').hidden=!open;$('open-filters').setAttribute('aria-expanded',String(open));if(open)$('close-filters').focus();else $('open-filters').focus();}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b||!data)return;
  if(b.dataset.open)openFish(b.dataset.open);
  else if(b.dataset.favorite){const key=b.dataset.favorite;toggleFavorite(key);const container=$('detail-dialog').open?$('detail-content'):$('results');container.querySelector(`[data-favorite="${key}"]`)?.focus({preventScroll:true});}
  else if(b.dataset.compare){const key=b.dataset.compare;toggleCompare(key);const container=$('detail-dialog').open?$('detail-content'):$('results');container.querySelector(`[data-compare="${key}"]`)?.focus({preventScroll:true});}
  else if(b.dataset.category){state.category=b.dataset.category;refresh();$('categories').querySelector(`[data-category="${state.category}"]`)?.focus({preventScroll:true});}
  else if(b.dataset.depth){setFilter('depth',state.depth===b.dataset.depth?'':b.dataset.depth);}
  else if(b.dataset.bottom){const key=b.dataset.bottom;setFilter('bottom',state.bottom.includes(key)?state.bottom.filter(k=>k!==key):[...state.bottom,key]);}
  else if(b.dataset.view){state.view=b.dataset.view;render();}
  else if(b.dataset.clear){const key=b.dataset.clear;if(key.startsWith('bottom:'))setFilter('bottom',state.bottom.filter(k=>k!==key.split(':')[1]));else setFilter(key,key==='available'?false:'');}
  else if(b.dataset.close)closeDialog(b.dataset.close);
  else if(b.dataset.item)filterFromDetail(b.dataset.kind,b.dataset.item);
  else if(b.dataset.place)filterFromDetail('location',b.dataset.place);
  else if(b.dataset.copy){const url=new URL(location.href);url.hash=`fish=${b.dataset.copy}`;try{await navigator.clipboard.writeText(url.href);notify('Ссылка на рыбу скопирована');}catch{notify('Ссылка на рыбу уже находится в адресной строке');}}
  else if(b.dataset.action==='reset')reset();
  else if(b.dataset.action==='clear-compare'){state.compare=[];render();}
  else if(b.dataset.action==='catalog'){state.favoritesOnly=false;reset();}
  else if(b.id==='run-compare')openComparison();
});
$('search').addEventListener('input',e=>{state.query=e.target.value;refresh();});
$('sort').addEventListener('change',e=>{state.sort=e.target.value;refresh();});
document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('change',()=>setFilter(el.dataset.filter,el.type==='checkbox'?el.checked:el.value)));
$('load-more').addEventListener('click',()=>{const oldCount=state.limit;state.limit+=24;render();$('results').querySelectorAll('[data-open]')[oldCount]?.focus({preventScroll:true});});
$('favorites-tab').addEventListener('click',()=>{state.favoritesOnly=true;refresh();});$('catalog-tab').addEventListener('click',()=>{state.favoritesOnly=false;refresh();});
for(const id of ['about-button','source-button','legend-button'])$(id).addEventListener('click',showAbout);
$('open-filters').addEventListener('click',()=>mobileFilters(true));$('close-filters').addEventListener('click',()=>mobileFilters(false));$('filter-shade').addEventListener('click',()=>mobileFilters(false));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('filters').classList.contains('open'))mobileFilters(false);if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!document.querySelector('dialog[open]')&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('search').focus();}});
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.classList.remove('modal-open');if(dialog.id==='detail-dialog'){activeFish=null;document.title='Атлас рыб · AnomFish';if(location.hash.startsWith('#fish='))history.replaceState(null,'',location.pathname+location.search);}});});
window.addEventListener('popstate',fromHash);window.addEventListener('hashchange',fromHash);
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'filter_fish_catalog',title:'Найти улов в атласе',description:'Set the visible fish catalog search and optional category. Clears other filters and returns matching fish.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:Object.keys(categories)}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.query!=='string'||input.query.length>200||(input.category&&!Object.hasOwn(categories,input.category)))throw new Error('Invalid query or category');Object.assign(state,{...defaults,bottom:[],query:input.query,category:input.category||'all',favoritesOnly:false});fillLocations();refresh();return{count:getRows().length,fish:getRows().map(f=>({key:f.key,name:f.name,weight:[f.minWeight,f.maxWeight],depth:f.depth}))};}});
  register({name:'open_fish_details',title:'Открыть карточку улова',description:'Open a catalog fish detail panel by its exact key.',inputSchema:{type:'object',properties:{key:{type:'string'}},required:['key'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.key!=='string'||!fishByKey.has(input.key))throw new Error('Unknown fish key');openFish(input.key);const f=fishByKey.get(input.key);return{key:f.key,name:f.name,opened:true};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
try{const response=await fetch('./data.json');if(!response.ok)throw new Error('Catalog unavailable');data=await response.json();fishByKey=new Map(data.fish.map(f=>[f.key,f]));locationByKey=new Map(data.locations.map(l=>[l.key,l]));state.favorites=[...new Set(state.favorites.filter(k=>fishByKey.has(k)))];$('total-count').textContent=data.fish.length;$('water-count').textContent=data.locations.filter(l=>l.enabled).length;document.querySelectorAll('button,input,select').forEach(el=>el.disabled=false);$('main').removeAttribute('aria-busy');fillOptions();render();fromHash();registerTools();}
catch(error){$('result-count').textContent='Каталог не загрузился';$('results').innerHTML=`<div class="empty-state">${icon('info')}<h2>Не удалось открыть данные</h2><p>Проверьте подключение и обновите страницу.</p><button class="secondary-button" id="retry">Попробовать снова</button></div>`;$('retry').addEventListener('click',()=>location.reload());console.error('Catalog failed',error);}
